#!/usr/bin/env python

utillib = bld.new_task_gen ('cc', 'staticlib')
utillib.find_sources_in_dirs ('.')
utillib.uselib='GLIB-2.0 GEE-1.0 GTHREAD'
utillib.packages = 'gee-1.0'
utillib.target='util-lib'
utillib.name='util-lib'
utillib.threading = True
utillib.install_path = None
