#!/usr/bin/env python

gemini = bld.new_task_gen ('cc', 'program')
gemini.find_sources_in_dirs ('.')
gemini.uselib='GLIB-2.0 VTE GEE-1.0 GTHREAD GTK+-2.0'
gemini.packages = 'vte gee-1.0'
gemini.target='gemini'
gemini.threading = True
